In [1]:
import torch
import torch.nn as nn

In [2]:
HIDDEN_SIZE = 1     # 히든개수
NUM_LAYERS = 1      # 양방향 * 층수
SEQ_LENGTH = 3      # 시퀀스 길이
BATCH_SIZE = 1      # 배치크기

### 데이터 및 초기 Hidden State
input = torch.randn(BATCH_SIZE, SEQ_LENGTH, 10)         # 입력 데이터 (배치크기, 시퀀스 길이, 피처길이)
h0 = torch.randn(NUM_LAYERS, BATCH_SIZE, HIDDEN_SIZE)   # 히든 초기값 (첫 번째 Hidden state 초기값)

### RNN 인스턴스 생성
rnn = nn.RNN(input_size=10, hidden_size=HIDDEN_SIZE, num_layers=NUM_LAYERS, batch_first=True)

### RNN 출력
output, hn = rnn(input, h0)

In [7]:
print(f'[INPUT DATA]\n- SHAPE : {input.shape}    DIM : {input.ndim}D')
print(input)

[INPUT DATA]
- SHAPE : torch.Size([1, 3, 10])    DIM : 3D
tensor([[[-0.0935,  1.0309, -0.1065,  0.2588,  0.5730,  0.8237, -0.6493,
           0.9478, -0.3394,  0.3470],
         [ 0.2725,  1.1158, -0.2433, -2.0610, -0.0228,  0.6511, -0.6514,
          -0.5838, -2.8151, -0.1927],
         [ 1.0441, -0.7733,  0.9519, -0.7485,  1.2616, -0.3369,  0.9378,
           0.4350, -1.0136, -1.0406]]])


In [6]:
print(f'[OUTPUT DATA]\n- SHAPE : {output.shape}    DIM : {output.ndim}D')
print(output)   # output (각각의 hidden state)

[OUTPUT DATA]
- SHAPE : torch.Size([1, 3, 1])    DIM : 3D
tensor([[[0.9081],
         [0.9986],
         [0.9022]]], grad_fn=<TransposeBackward1>)


In [8]:
print(f'[hn DATA]\n- SHAPE : {hn.shape}    DIM : {hn.ndim}D')
print(hn)   # 마지막 hidden stte (output 끝 값과 동일)

[hn DATA]
- SHAPE : torch.Size([1, 1, 1])    DIM : 3D
tensor([[[0.9022]]], grad_fn=<StackBackward0>)


In [11]:
print(f'[RNN PARAMETERS]')
for name, param in rnn.named_parameters():
    print(f'----[{name}]\n{param}\n')

[RNN PARAMETERS]
----[weight_ih_l0]
Parameter containing:
tensor([[-0.8951, -0.1725,  0.5153, -0.4521, -0.6114,  0.3087,  0.4104,  0.5817,
         -0.9892,  0.1526]], requires_grad=True)

----[weight_hh_l0]
Parameter containing:
tensor([[-0.5120]], requires_grad=True)

----[bias_ih_l0]
Parameter containing:
tensor([0.9010], requires_grad=True)

----[bias_hh_l0]
Parameter containing:
tensor([0.4602], requires_grad=True)



In [ ]:
class abcd:

    def __init__(self, a, b, c):
        a : int
        b : float
        c : str

        print(a)